# SPDX-FileCopyrightText: Copyright 2026 Automat Authors
# SPDX-License-Identifier: MIT

# Warning: coded with a stochastic parrot

import extension_helper
import build

hook = extension_helper.ExtensionHelper('Babl', globals())

hook.FetchFromGit('https://gitlab.gnome.org/GNOME/babl.git', 'BABL_0_1_118')

# Babl is linked statically, and its extensions are compiled into the library
# instead of being dlopened: the extensions are not only SIMD fast paths -
# CIE.c, HSV.c, and related files REGISTER the format families GEGL operations look
# up by name (babl_format("CIE LCH(ab) alpha float") aborts without them).
# Each chosen extension is wrapped in a generated TU that renames its
# entry points, and a generated registrar loads them from
# babl_extension_base() with the same extender bookkeeping the dynamic
# loader would use. Only the arch-gated SIMD variants stay out. Tests, tools
# and the CLI are dropped; the def-file consistency check expects a shared
# library, and the wrap-build dependency must not reference the removed
# extensions directory.

# Everything upstream ships except the extensions needing ISA flags past the
# x86-64 baseline (their formats and conversions are covered by the portable
# ones; they only accelerate).
STATIC_EXTENSIONS = [
  'CIE', 'HCY', 'HSL', 'HSV', 'cairo', 'double', 'fast-float', 'float',
  'formats', 'gegl-fixups', 'gggl', 'gggl-lies', 'gggl-table',
  'gggl-table-lies', 'gimp-8bit', 'grey', 'half', 'naive-CMYK', 'oklab',
  'simple', 'two-table', 'u16', 'u32', 'ycbcr',
]

def _mangle(name):
  return name.replace('-', '_')

def _patch_static_extensions(marker):
  path = hook.src_dir / 'meson.build'
  text = path.read_text()
  replacements = [
    ("""subdir('babl')
subdir('extensions')
subdir('tests')
subdir('tools')
if build_docs
  subdir('docs')
endif
subdir('bin')""",
     "subdir('babl')"),
    ("    build_by_default: true,\n", "    build_by_default: false,\n"),
    ("    'babl_path'   : babl_extensions_build_dir,\n",
     "    'babl_path'   : babl_library_build_dir,\n"),
  ]
  for needle, replacement in replacements:
    if needle in text:
      text = text.replace(needle, replacement)
    elif replacement not in text:
      raise RuntimeError(f'Babl patch no longer applies: {needle!r} not found in {path}')
  path.write_text(text)

  # One wrapper TU per extension: rename the entry points, then include the
  # extension source unchanged. BABL_SIMDFREE must stay UNDEFINED: with it,
  # babl-verify-cpu.inc makes init() defer to the x86-64-v2/v3 module variants
  # on capable processors - it returns success having registered nothing, and
  # those variants are exactly what this build does not ship. Undefined, the
  # verify macro is a no-op and the generic code paths register always.
  babl_dir = hook.src_dir / 'babl'
  wrapper_names = []
  for ext in STATIC_EXTENSIONS:
    wrapper = f'ext-{ext}.c'
    wrapper_names.append(wrapper)
    (babl_dir / wrapper).write_text(
      f'/* Generated by src/babl.py: extension {ext}.c compiled into the library. */\n'
      f'#define init babl_ext_init_{_mangle(ext)}\n'
      f'#define destroy babl_ext_destroy_{_mangle(ext)}\n'
      f'#include "../extensions/{ext}.c"\n')

  # The registrar: extension_new/babl_set_extender are file-local to
  # babl-extension.c, so it is included there and called from
  # babl_extension_base().
  decls = '\n'.join(f'int babl_ext_init_{_mangle(e)} (void);' for e in STATIC_EXTENSIONS)
  entries = '\n'.join(f'    {{ "{e}", babl_ext_init_{_mangle(e)} }},'
                      for e in STATIC_EXTENSIONS)
  (babl_dir / 'babl-static-extensions.inc').write_text(f'''\
/* Generated by src/babl.py: registers the statically linked extensions. */
{decls}

static void
babl_init_static_extensions (void)
{{
  static const struct {{ const char *name; int (*init) (void); }} exts[] = {{
{entries}
  }};
  unsigned i;
  for (i = 0; i < sizeof (exts) / sizeof (exts[0]); i++)
    {{
      Babl *babl = extension_new (exts[i].name, NULL, NULL);
      babl_set_extender (babl);
      if (exts[i].init () == 0)
        babl_db_insert (db, babl);
      else
        babl_free (babl);
      babl_set_extender (NULL);
    }}
}}
''')

  path = babl_dir / 'babl-extension.c'
  text = path.read_text()
  needle = 'Babl *\nbabl_extension_base (void)'
  if needle not in text:
    raise RuntimeError(f'Babl patch no longer applies: {needle!r} not found in {path}')
  text = text.replace(needle,
                      '#include "babl-static-extensions.inc"\n\n' + needle)
  needle = '''  babl_set_extender (NULL);
  return babl;
}'''
  if needle not in text:
    raise RuntimeError(f'Babl patch no longer applies: {needle!r} not found in {path}')
  text = text.replace(needle, '''  babl_set_extender (NULL);
  babl_init_static_extensions ();
  return babl;
}''', 1)
  path.write_text(text)

  path = babl_dir / 'meson.build'
  text = path.read_text()
  needle = 'babl_sources = files(\n'
  if needle not in text:
    raise RuntimeError(f'Babl patch no longer applies: {needle!r} not found in {path}')
  wrapper_lines = ''.join(f"  '{w}',\n" for w in wrapper_names)
  text = text.replace(needle, needle + wrapper_lines, 1)
  path.write_text(text)
  marker.touch()
hook.PatchSources(_patch_static_extensions)

hook.ConfigureWithMeson(build.PREFIX / 'include' / 'babl-0.1' / 'babl' / 'babl.h')
if build.platform == 'win32':
  # MSVC headers only define M_LN2 & friends under _USE_MATH_DEFINES.
  hook.ConfigureOption('c_args', '-D_USE_MATH_DEFINES')
hook.ConfigureOptions(**{
  'with-docs': 'false',
  'enable-gir': 'false',
  'enable-vapi': 'false',
  'gi-docgen': 'disabled',
  'with-lcms': 'disabled',
})
hook.InstallWhenIncluded(r'babl/babl\.h')
hook.AddCompileArgs(f'-I{build.PREFIX / "include" / "babl-0.1"}')
if build.platform == 'win32':
  hook.AddLinkArg(str(build.PREFIX / 'lib64' / 'libbabl-0.1.a'))
else:
  hook.AddLinkArgs('-lbabl-0.1', '-lm', '-ldl', '-pthread')
