// SPDX-FileCopyrightText: Copyright 2024 Automat Authors
// SPDX-License-Identifier: MIT
#pragma once

#include "keyboard.hh"

namespace x11 {
enum class KeyCode {
  Unknown = 0,
  Esc = 9,
  Digit1 = 10,
  Digit2 = 11,
  Digit3 = 12,
  Digit4 = 13,
  Digit5 = 14,
  Digit6 = 15,
  Digit7 = 16,
  Digit8 = 17,
  Digit9 = 18,
  Digit0 = 19,
  Minus = 20,
  Equals = 21,
  Backspace = 22,
  Tab = 23,
  Q = 24,
  W = 25,
  E = 26,
  R = 27,
  T = 28,
  Y = 29,
  U = 30,
  I = 31,
  O = 32,
  P = 33,
  LeftBracket = 34,
  RightBracket = 35,
  Return = 36,
  CtrlLeft = 37,
  A = 38,
  S = 39,
  D = 40,
  F = 41,
  G = 42,
  H = 43,
  J = 44,
  K = 45,
  L = 46,
  Semicolon = 47,
  Apostrophe = 48,
  Grave = 49,
  ShiftLeft = 50,
  BackSlash = 51,
  Z = 52,
  X = 53,
  C = 54,
  V = 55,
  B = 56,
  N = 57,
  M = 58,
  Comma = 59,
  Dot = 60,
  Slash = 61,
  ShiftRight = 62,
  KpMultiply = 63,
  AltLeft = 64,
  Space = 65,
  CapsLock = 66,
  F1 = 67,
  F2 = 68,
  F3 = 69,
  F4 = 70,
  F5 = 71,
  F6 = 72,
  F7 = 73,
  F8 = 74,
  F9 = 75,
  F10 = 76,
  NumLock = 77,
  ScrollLock = 78,
  Kp7 = 79,
  Kp8 = 80,
  Kp9 = 81,
  KpMinus = 82,
  Kp4 = 83,
  Kp5 = 84,
  Kp6 = 85,
  KpPlus = 86,
  Kp1 = 87,
  Kp2 = 88,
  Kp3 = 89,
  Kp0 = 90,
  KpDot = 91,
  Unknown1 = 92,         // ???
  Zenkaku_Hankaku = 93,  // ???
  International = 94,    // ???
  F11 = 95,
  F12 = 96,

  OEM_102 = 97,   // ???
  Katakana = 98,  // ???
  Hiragana = 99,  // ???
  Henkan = 100,   // ???
  Katakana_Hiragana = 101,
  Muhenkan = 102,  // ???

  KpSeparator = 103,
  KpEnter = 104,
  CtrlRight = 105,
  KpDivide = 106,
  PrintScrn = 107,
  AltRight = 108,
  LineFeed = 109,  // ???
  Home = 110,
  Up = 111,
  PageUp = 112,
  Left = 113,
  Right = 114,
  End = 115,
  Down = 116,
  PageDown = 117,
  Insert = 118,
  Delete = 119,
  Macro = 120,  // ???
  Mute = 121,
  VolumeDown = 122,
  VolumeUp = 123,
  Power = 124,
  KpEqual = 125,
  KpPlusMinus = 126,
  Pause = 127,
  MediaLaunchApp1 = 128,
  KpDecimal = 129,
  Hangul = 130,  // ???
  Hanja = 131,   // ???
  Yen = 132,
  SuperLeft = 133,
  SuperRight = 134,
  Compose = 135,
};

constexpr KeyCode kKeyCodesArray[] = {
    KeyCode::Esc,        KeyCode::Digit1,      KeyCode::Digit2,
    KeyCode::Digit3,     KeyCode::Digit4,      KeyCode::Digit5,
    KeyCode::Digit6,     KeyCode::Digit7,      KeyCode::Digit8,
    KeyCode::Digit9,     KeyCode::Digit0,      KeyCode::Minus,
    KeyCode::Equals,     KeyCode::Backspace,   KeyCode::Tab,
    KeyCode::Q,          KeyCode::W,           KeyCode::E,
    KeyCode::R,          KeyCode::T,           KeyCode::Y,
    KeyCode::U,          KeyCode::I,           KeyCode::O,
    KeyCode::P,          KeyCode::LeftBracket, KeyCode::RightBracket,
    KeyCode::Return,     KeyCode::CtrlLeft,    KeyCode::A,
    KeyCode::S,          KeyCode::D,           KeyCode::F,
    KeyCode::G,          KeyCode::H,           KeyCode::J,
    KeyCode::K,          KeyCode::L,           KeyCode::Semicolon,
    KeyCode::Apostrophe, KeyCode::Grave,       KeyCode::ShiftLeft,
    KeyCode::BackSlash,  KeyCode::Z,           KeyCode::X,
    KeyCode::C,          KeyCode::V,           KeyCode::B,
    KeyCode::N,          KeyCode::M,           KeyCode::Comma,
    KeyCode::Dot,        KeyCode::Slash,       KeyCode::ShiftRight,
    KeyCode::KpMultiply, KeyCode::AltLeft,     KeyCode::Space,
    KeyCode::CapsLock,   KeyCode::F1,          KeyCode::F2,
    KeyCode::F3,         KeyCode::F4,          KeyCode::F5,
    KeyCode::F6,         KeyCode::F7,          KeyCode::F8,
    KeyCode::F9,         KeyCode::F10,         KeyCode::NumLock,
    KeyCode::ScrollLock, KeyCode::Kp7,         KeyCode::Kp8,
    KeyCode::Kp9,        KeyCode::KpMinus,     KeyCode::Kp4,
    KeyCode::Kp5,        KeyCode::Kp6,         KeyCode::KpPlus,
    KeyCode::Kp1,        KeyCode::Kp2,         KeyCode::Kp3,
    KeyCode::Kp0,        KeyCode::KpDot,       KeyCode::International,
    KeyCode::F11,        KeyCode::F12,         KeyCode::Home,
    KeyCode::Up,         KeyCode::PageUp,      KeyCode::Left,
    KeyCode::Right,      KeyCode::Down,        KeyCode::End,
    KeyCode::PageDown,   KeyCode::Insert,      KeyCode::Delete,
    KeyCode::KpEnter,    KeyCode::CtrlRight,   KeyCode::Pause,
    KeyCode::PrintScrn,  KeyCode::KpDivide,    KeyCode::AltRight,
    KeyCode::SuperLeft,  KeyCode::SuperRight,  KeyCode::Compose,
};

automat::gui::AnsiKey X11KeyCodeToKey(KeyCode key_code);
KeyCode KeyToX11KeyCode(automat::gui::AnsiKey key);

}  // namespace x11