#include "x11.hh"

namespace x11 {

using automat::gui::AnsiKey;
using enum automat::gui::AnsiKey;

AnsiKey X11KeyCodeToKey(KeyCode key_code) {
  switch (key_code) {
    case KeyCode::W:
      return W;
    case KeyCode::A:
      return A;
    case KeyCode::S:
      return S;
    case KeyCode::D:
      return D;
    default:
      return Unknown;
  }
}

KeyCode KeyToX11KeyCode(AnsiKey key) {
  switch (key) {
    case Unknown:
    case Count:
      return KeyCode::Unknown;
    case Escape:
      return KeyCode::Esc;
    case F1:
      return KeyCode::F1;
    case F2:
      return KeyCode::F2;
    case F3:
      return KeyCode::F3;
    case F4:
      return KeyCode::F4;
    case F5:
      return KeyCode::F5;
    case F6:
      return KeyCode::F6;
    case F7:
      return KeyCode::F7;
    case F8:
      return KeyCode::F8;
    case F9:
      return KeyCode::F9;
    case F10:
      return KeyCode::F10;
    case F11:
      return KeyCode::F11;
    case F12:
      return KeyCode::F12;
    case PrintScreen:
      return KeyCode::PrintScrn;
    case ScrollLock:
      return KeyCode::ScrollLock;
    case Pause:
      return KeyCode::Pause;
    case Insert:
      return KeyCode::Insert;
    case Delete:
      return KeyCode::Delete;
    case Home:
      return KeyCode::Home;
    case End:
      return KeyCode::End;
    case PageUp:
      return KeyCode::PageUp;
    case PageDown:
      return KeyCode::PageDown;
    case Up:
      return KeyCode::Up;
    case Down:
      return KeyCode::Down;
    case Left:
      return KeyCode::Left;
    case Right:
      return KeyCode::Right;
    case NumLock:
      return KeyCode::NumLock;
    case NumpadDivide:
      return KeyCode::KpDivide;
    case NumpadMultiply:
      return KeyCode::KpMultiply;
    case NumpadMinus:
      return KeyCode::KpMinus;
    case NumpadPlus:
      return KeyCode::KpPlus;
    case NumpadEnter:
      return KeyCode::KpEnter;
    case NumpadPeriod:
      return KeyCode::KpDot;
    case Numpad0:
      return KeyCode::Kp0;
    case Numpad1:
      return KeyCode::Kp1;
    case Numpad2:
      return KeyCode::Kp2;
    case Numpad3:
      return KeyCode::Kp3;
    case Numpad4:
      return KeyCode::Kp4;
    case Numpad5:
      return KeyCode::Kp5;
    case Numpad6:
      return KeyCode::Kp6;
    case Numpad7:
      return KeyCode::Kp7;
    case Numpad8:
      return KeyCode::Kp8;
    case Numpad9:
      return KeyCode::Kp9;
    case Grave:
      return KeyCode::Backtick;
    case Digit1:
      return KeyCode::Digit1;
    case Digit2:
      return KeyCode::Digit2;
    case Digit3:
      return KeyCode::Digit3;
    case Digit4:
      return KeyCode::Digit4;
    case Digit5:
      return KeyCode::Digit5;
    case Digit6:
      return KeyCode::Digit6;
    case Digit7:
      return KeyCode::Digit7;
    case Digit8:
      return KeyCode::Digit8;
    case Digit9:
      return KeyCode::Digit9;
    case Digit0:
      return KeyCode::Digit0;
    case Minus:
      return KeyCode::Minus;
    case Equals:
      return KeyCode::Equals;
    case Backspace:
      return KeyCode::Backspace;
    case Tab:
      return KeyCode::Tab;
    case Q:
      return KeyCode::Q;
    case W:
      return KeyCode::W;
    case E:
      return KeyCode::E;
    case R:
      return KeyCode::R;
    case T:
      return KeyCode::T;
    case Y:
      return KeyCode::Y;
    case U:
      return KeyCode::U;
    case I:
      return KeyCode::I;
    case O:
      return KeyCode::O;
    case P:
      return KeyCode::P;
    case BracketLeft:
      return KeyCode::LeftBracket;
    case BracketRight:
      return KeyCode::RightBracket;
    case Backslash:
      return KeyCode::BackSlash;
    case CapsLock:
      return KeyCode::CapsLock;
    case A:
      return KeyCode::A;
    case S:
      return KeyCode::S;
    case D:
      return KeyCode::D;
    case F:
      return KeyCode::F;
    case G:
      return KeyCode::G;
    case H:
      return KeyCode::H;
    case J:
      return KeyCode::J;
    case K:
      return KeyCode::K;
    case L:
      return KeyCode::L;
    case Semicolon:
      return KeyCode::Semicolon;
    case Apostrophe:
      return KeyCode::Apostrophe;
    case Enter:
      return KeyCode::Return;
    case ShiftLeft:
      return KeyCode::ShiftLeft;
    case Z:
      return KeyCode::Z;
    case X:
      return KeyCode::X;
    case C:
      return KeyCode::C;
    case V:
      return KeyCode::V;
    case B:
      return KeyCode::B;
    case N:
      return KeyCode::N;
    case M:
      return KeyCode::M;
    case Comma:
      return KeyCode::Comma;
    case Period:
      return KeyCode::Dot;
    case Slash:
      return KeyCode::Slash;
    case ShiftRight:
      return KeyCode::ShiftRight;
    case ControlLeft:
      return KeyCode::CtrlLeft;
    case SuperLeft:
      return KeyCode::SuperLeft;
    case AltLeft:
      return KeyCode::AltLeft;
    case Space:
      return KeyCode::Space;
    case AltRight:
      return KeyCode::AltRight;
    case SuperRight:
      return KeyCode::SuperRight;
    case Application:
      return KeyCode::Menu;
    case ControlRight:
      return KeyCode::CtrlRight;
  }
}

}  // namespace x11