name: Build

on:
  workflow_dispatch:

jobs:
  windows_release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Restore Skia
        id: cache-skia-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            build/skia
          key: ${{ runner.os }}-skia

      - name: Build
        run: python run.py 'link release_automat'

      - name: Cache Skia
        id: cache-skia-save
        uses: actions/cache/save@v4
        with:
          path: |
            build/skia
          key: ${{ steps.cache-skia-restore.outputs.cache-primary-key }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Windows Executable
          path: build/release_automat.exe
          if-no-files-found: error
