name: Build

on:
  workflow_dispatch:

jobs:
  windows_release:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Restore dependencies from cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            build/Release/Skia
            build/Release/vk-bootstrap
            build/vulkan-headers
            build/rapidjson
            build/depot_tools
            build/FastTrigo
          key: ${{ runner.os }}-deps

      - name: Build
        run: python run.py 'link release_automat'

      - name: Cache dependencies
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            build/Release/Skia
            build/Release/vk-bootstrap
            build/vulkan-headers
            build/rapidjson
            build/depot_tools
            build/FastTrigo
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Windows Executable
          path: build/Release/automat.exe
          if-no-files-found: error

  linux_release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore dependencies from cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            build/
          key: ${{ runner.os }}-deps

      - name: Build
        run: python run.py 'link release_automat'

      - name: Start upterm session on failure
        uses: lhotari/action-upterm@v1
        if: ${{ failure() }}
        with:
          wait-timeout-minutes: 10

      - name: Cache dependencies
        id: cache-save
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            build/
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Linux Executable
          path: build/Release/automat
          if-no-files-found: error
