name: Build

on:
  workflow_dispatch:

jobs:
  windows_release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build
        run: python run.py 'link release_automat'

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Windows Executable
          path: build/release_automat.exe
          if-no-files-found: error
