name: Build

on:
  workflow_dispatch:

jobs:
  windows_release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Restore dependencies from cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            build/skia
            build/vk-bootstrap
            build/vulkan-headers
            build/rapidjson
            build/depot_tools
            build/FastTrigo
          key: ${{ runner.os }}-deps

      - name: Build
        run: python run.py 'link release_automat'

      - name: Cache dependencies
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            build/skia
            build/vk-bootstrap
            build/vulkan-headers
            build/rapidjson
            build/depot_tools
            build/FastTrigo
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Windows Executable
          path: build/release_automat.exe
          if-no-files-found: error
