name: Build

on:
  workflow_dispatch:

jobs:
  windows_release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build
        run: ./run.py 'link release_automat'

      # - name: Upload
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: dist
